id: PD47D2CAD
initial_creation_type: input
source_metadata:
  title: Siṃhamukhā Series
  language: fr
  description: 'Texts related to Siṃhamukhā/Siṃhamukhī or Siṃhavaktrā (seng ge gdong
    ma), the Lion-Faced Ḍākinī:'
  volume:
    3148e66becdf4b6f8544c712f5c8a2f4:
      title: A Daily 'Hand-Clapping' Practice of Siṃhamukhā
      parent: Averting Obstacles
    1367268692244d8ba0db2778273ac9e8:
      title: The History of the Hearing Lineage of the Profound and Secret Practice
        of Siṃhamukhā
      parent: History
    4aa70f6df5e14a8daf5149e23e848967:
      title: Siṃhamukhā Lineage Prayer
      parent: Lineage Prayers
created_at: '2022-03-01T05:49:02.016249'
last_modified_at: '2022-03-01T05:49:02.016252'
